### PR TITLE
Use OTel prescribed way of recording exception and span status

### PR DESCRIPTION
**Pull request by jcmackie**
Hi again @justindsmith!

Even though the preview of Prisma tracing is done, we are still using your lovely library so I thought I'd do an RFC as a PR. I hope you don't mind that I didn't create an issue for it.

The crux of this PR is that I would like the "x-ray" exporter to pick up exceptions and error that happen in the DB spans.
Currently the exporter [decides if there was a problem](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4741a95b43ce988156ffcc80dd749cf9150cc7b6/exporter/awsxrayexporter/internal/translator/cause.go#L57) if either:

- There are [OTel exceptions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/) in the spans
- Using the OpenCensus model of checking the http_status_text attributes (this is my very quick and poor read of the code)

Seeing as we are using an OTel client, I thought it would be useful to use the functions provided by the client to record the status and the exception.

The span status is now recorded in the special [`Status`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) field.
The exception is now recorded as an Event, which has it's own [semantic convention](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/) in the OTel spec.

#### EDIT: as discussed I have re-added the previous exception instrumentation to backwards compatibility.

Using ConsoleSpanExporter I can show the before and after of this change.

### Before
```
{
  traceId: '630ea5e26005831465a88e7b649768c2',
  parentId: 'd24289ed385cf47f',
  name: '$queryRaw',
  id: '59e5b6b15574f6d0',
  kind: 2,
  timestamp: 1661904354991963,
  duration: 8625,
  attributes: {
    component: 'prisma',
    'db.statement': 'SELECT client_addr, query, state FROM pg_stat_activity;',
    'db.system': 'postgresql',
    error: true,
    'exception.message': '\n' +
      'Invalid `prisma.$queryRaw()` invocation:\n' +
      '\n' +
      '\n' +
      "  Can't reach database server at `localhost`:`5432`\n" +
      '\n' +
      'Please make sure your database server is running at `localhost`:`5432`.',
    'exception.stacktrace': 'Error: \n' +
      'Invalid `prisma.$queryRaw()` invocation:\n' +
      '\n' +
      '\n' +
      "  Can't reach database server at `localhost`:`5432`\n" +
      '\n' +
      'Please make sure your database server is running at `localhost`:`5432`.\n' +
      '    at RequestHandler.request (/Users/jmackie/work/misc_tools/my_app/node_modules/@prisma/client/runtime/index.js:49028:15)\n' +
      '    at async Proxy._request (/Users/jmackie/work/misc_tools/my_app/node_modules/@prisma/client/runtime/index.js:49919:18)'
  },
  status: { code: 0 },
  events: [],
  links: []
}
```

### After
```
{
  traceId: '63103029aef3058990fbb0bf16926451',
  parentId: '0be65fc261a29d90',
  name: '$queryRaw',
  id: '7c53adf4bbb14ba2',
  kind: 2,
  timestamp: 1662005289301407,
  duration: 9414,
  attributes: {
    component: 'prisma',
    'db.statement': 'SELECT client_addr, query, state FROM pg_stat_activity;',
    'db.system': 'postgresql',
    error: true,
    'exception.message': '\n' +
      'Invalid `prisma.$queryRaw()` invocation:\n' +
      '\n' +
      '\n' +
      "  Can't reach database server at `localhost`:`5432`\n" +
      '\n' +
      'Please make sure your database server is running at `localhost`:`5432`.',
    'exception.stacktrace': 'Error: \n' +
      'Invalid `prisma.$queryRaw()` invocation:\n' +
      '\n' +
      '\n' +
      "  Can't reach database server at `localhost`:`5432`\n" +
      '\n' +
      'Please make sure your database server is running at `localhost`:`5432`.\n' +
      '    at RequestHandler.request (/Users/jmackie/work/misc_tools/Hermes/node_modules/@prisma/client/runtime/index.js:49028:15)\n' +
      '    at async Proxy._request (/Users/jmackie/work/misc_tools/Hermes/node_modules/@prisma/client/runtime/index.js:49919:18)'
  },
  status: { code: 2 },
  events: [
    {
      name: 'exception',
      attributes: {
        'exception.type': 'Error',
        'exception.message': '\n' +
          'Invalid `prisma.$queryRaw()` invocation:\n' +
          '\n' +
          '\n' +
          "  Can't reach database server at `localhost`:`5432`\n" +
          '\n' +
          'Please make sure your database server is running at `localhost`:`5432`.',
        'exception.stacktrace': 'Error: \n' +
          'Invalid `prisma.$queryRaw()` invocation:\n' +
          '\n' +
          '\n' +
          "  Can't reach database server at `localhost`:`5432`\n" +
          '\n' +
          'Please make sure your database server is running at `localhost`:`5432`.\n' +
          '    at RequestHandler.request (/Users/jmackie/work/misc_tools/Hermes/node_modules/@prisma/client/runtime/index.js:49028:15)\n' +
          '    at async Proxy._request (/Users/jmackie/work/misc_tools/Hermes/node_modules/@prisma/client/runtime/index.js:49919:18)'
      },
      time: [ 1662005289, 310640818 ]
    }
  ],
  links: []
}
```

### CODE REVIEW

**Comment by jcmackie** [comment]
Hi @justindsmith,

Great feedback as usual.

> I'm not super keen on more configuration, so I'm leaning towards (2) to maintain some compatibility for existing users. The drawback is that we "double publish" error values, but it might make it easier for consumers of the raw attribute outputs.
I agree with your thoughts here. I was thinking about whether it's okay or not to introduce this potentially breaking change, but your comment has clarified things for me.
While it does seem "inefficient" to publish the error information twice in the same span, I agree that not breaking things for your other users makes a lot of sense.

I'll make the change necessary to return the previous instrumentation.

**Review by justindsmith — APPROVED** [review]
Looks good!

**Comment by justindsmith** [comment]
Published under `opentelemetry-instrumentation-prisma-client@0.1.0`. Thanks @jcmackie! 🙂

**Comment by jcmackie** [comment]
Awesome, thanks again @justindsmith!!

**Pull request merged**
