### PR TITLE
Report errors as exception events

### PR DESCRIPTION
**Pull request by unflxw**
The current recommended way to report errors in OpenTelemetry is by using span exception events with the `span.recordException()` method. This PR modifies the integration so that it reports exceptions in this manner.

A configuration option that keeps the previous behaviour (errors as span attributes) has been added, but the default behaviour is now to report errors as span exception events. Let me know if you'd rather not have the configuration option, or have it with a different default.

Please let me know if there are any questions!

---

### [Rearrange Remix tests](https://github.com/justindsmith/opentelemetry-instrumentations-js/commit/08dcce5605bed52b386242af0e072f0b2a31a96f)

Create meaningful expectations for the different span types and
attributes, which can be reused across tests.

Some of the expectations in this commit regarding error events will
be used in the next commit.

### [Send errors as exception events](https://github.com/justindsmith/opentelemetry-instrumentations-js/commit/be241a2ef9841e2727faf3275fbe3c9d8ccebf3a)

Before this commit, the Remix instrumentation would report errors
with a series of attributes, containing whether an error took place,
the error message and its stack.

The recommended way to report errors in OpenTelemetry today is to
use an exception event and set the span status to error.

For backwards compatibility, a `legacyErrorAttributes` configuration
option is added, which re-enables attribute-based error reporting.

### CODE REVIEW

**Comment by unflxw** [comment]
I've changed it so that it imports `ReadableSpan` from `sdk-trace-base`, not `sdk-trace-node`. If that doesn't fix it we can compute it from the return type of `getTestSpans`:

```ts
type ReadableSpan = ReturnType<typeof getTestSpans>[0];
```

**Comment by unflxw** [comment]
The error I'm getting in the tests, I can reproduce in `main` -- without my changes, that is. I'll have a look at fixing it.

**Comment by unflxw** [comment]
This new error, I cannot reproduce locally at all. I'm at a loss on what to do here. :(

**Comment by justindsmith** [comment]
Unfortunately I’m not in place to do a deeper look, but are you running `tav` locally or just the tests? A very quick peek at the test logs looks like your changes might be breaking when 1.15.0 of remix is installed? I can take a closer look and help out more tomorrow!

**Comment by unflxw** [comment]
`tav` (specifically, `yarn run test:ci` from the `opentelemetry-remix` folder) runs fine from beginning to end in my local machine. Searching for the error message online, I found references to this happening when different versions of `@types/react` are installed in a workspace. Maybe it only happens locally when running `yarn run test:ci:all` from the workspace root? I'll give that a try.

**Comment by unflxw** [comment]
The issue can be reproduced by running `yarn test:ci:changed` in the `unflxw/fix-tests-remix-server-runtime-1.9.1`. The issue is not introduced by this branch, it is present on `main` -- it's just an easy reproduction case, in that it differs from `origin/main` by one commit, and this allows `tav` to continue past version `1.9.1`.

I have not been able to figure out a fix. The root cause, I believe, is that `@remix/server-runtime@1.5.0` requests `@types/react` in `dependencies`, not in `devDependencies`. This somehow causes two different versions of the type definitions to exist, which `tsc` rejects as they clash with each other.

Going by the error messages, one of them seems to be installed at the workspace root's `node_modules`, while the other seems to be installed in the instrumentation's `node_modules`, and one of them is installed by `@remix/server-runtime`, while the other is installed by `instrumentation-remix`.

Here's what I've tried:
- Putting a `resolutions` field for `@types/react` or `**/@types/react` in the workspace root's `package.json`, or in the instrumentation's `package.json`. This doesn't do anything, because `tav` uses `npm` to install dependencies.
- Putting an `override` field for `@types/react` in the workspace root's `package.json`, or in the instrumentation's `package.json`, or in both, referencing the same version number. This does seem to do something, but the error persists. 
- Putting a `peerDependency` field for `@types/react` in the `.tav.yml` file. I don't know why I thought this would do anything.
- Putting a `typeRoots` field in the `tsconfig.json`, or the `tsconfig.base.json` in the workspace root, pointing at `../../node_modules/@types`, or at `./node_modules/@types`, in an attempt to select only one of the two sources of type definitions. I am unsure as to whether this did anything at all, but if it did, it did not fix the issue.

I am out of ideas.

**Comment by justindsmith** [comment]
Thanks @unflxw! You're a saint for pushing through the failing tests. I got them working again by just bumping the version of the react types (and react itself to match). I bumped the remix versions to latest as well, just to stay up-to-date. I also fixed the prettier lint issue and updated the docs to show the new configuration and emitted span structure. Once this goes through I'll release a `0.4.0` version with your changes!

**Review by justindsmith — APPROVED** [review]

**Comment by justindsmith** [comment]
Changes have been published into v0.4.0: https://www.npmjs.com/package/opentelemetry-instrumentation-remix/v/0.4.0

Thank you again for the PR! 🙂

**Comment by unflxw** [comment]
Thank you so much for fixing the tests @justindsmith! I'm glad you were able to find a solution 🙌 🎉

**Pull request merged**
